url: https://node.left.local
verbosity: debug
strictmode: false
internalratelimiter: false
http:
  log: metadata-and-body
  internal:
    address: :8081
auth:
  contractvalidators:
    - dummy
  irma:
    autoupdateschemas: false
policy:
  directory: /nuts/policies
discovery:
  definitions:
    directory: /nuts/discovery
  server:
    ids:
      - urn:nuts.nl:usecase:eOverdrachtDemo2024
