---
name: 'Build Docker images'

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: version
        shell: bash
        run: |
          echo "::set-output name=git_commit::$(echo ${GITHUB_SHA})"
          echo "::set-output name=git_branch::$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=git_version::$(git name-rev --tags --name-only $(git rev-parse HEAD))"

      - name: Print version information
        run: |
          echo "Commit: ${{ steps.version.outputs.git_commit }}"
          echo "Branch: ${{ steps.version.outputs.git_branch }}"
          echo "Version: ${{ steps.version.outputs.git_version }}"

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: nutsfoundation/nuts-demo-ehr
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            GIT_VERSION=${{ steps.version.outputs.git_version }}
            GIT_COMMIT=${{ steps.version.outputs.git_commit }}
            GIT_BRANCH=${{ steps.version.outputs.git_branch }}
