---
name: 'Go Tests'

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # use go version from go.mod.
          go-version-file: 'go.mod'
      - name: Go Test
        run: |
          # we don't care about the assets
          mkdir -p web/dist/ && \
            touch web/dist/_example && \
            go test ./...
